---
name: Super-Linter

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  super-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Super-Linter
        uses: docker://github/super-linter:latest
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: '^TheBetaWeb/base/migrations/.*'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
