---
name: Code Validation

on: 
  push:
    branches: [main]

jobs:
  super-lint:
    name: Lint - main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Super-Linter
        uses: docker://github/super-linter:latest
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: /.*(base\/migrations|static\/images|\.github|\.vscode|\.html|\.css|pull_request_template).*/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: false
          VALIDATE_HTML: false
